### ISSUE TITLE
specify time

### ISSUE THREAD

**Issue by smilesun** [jdblischak/smk-simple-slurm#15]
in sbatch, one could specify
```
#!/bin/bash
#SBATCH -p gpu_p
#SBATCH --qos=gpu
#SBATCH --gres=gpu:1
#SBATCH -c 1
#SBATCH --mem=32G
#SBATCH -t 48:00:00
#SBATCH --nice=10000 
```

where -t specify the time, is there an option to do that as well using yaml here with snakemake? 

Since I constantly got out-of-memory error running my GPU job, i wonder if that is a time out error?

**Comment by jdblischak** [comment]
You can update this profile to pass any valid `sbatch` argument. The `--time` flag is explicitly used as a demonstration in the README:
 
https://github.com/jdblischak/smk-simple-slurm#a-variable-argument-to-sbatch-eg---time

**Comment by jdblischak** [comment]
Also note that you can define time as an integer or a string. There are existing examples for both strategies: [`time-integer`](https://github.com/jdblischak/smk-simple-slurm/tree/main/examples/time-integer) and [`time-string`](https://github.com/jdblischak/smk-simple-slurm/tree/main/examples/time-string)
