### ISSUE TITLE
Conditional resource in the sbatch command

### ISSUE THREAD

**Issue by TomHarrop** [jdblischak/smk-simple-slurm#16]
Hi John,

I'm still finding these profiles super useful.

Do you know if there's a way to include a resource only if it's specified? My cluster has a lot of partitions/queues. The advice is to let SLURM pick one based on the requested resources, but there are some cases where I'd need to override that.

I tried a bunch of stuff like the following but couldn't hit on anything that worked.

```yaml
cluster:
  sbatch
    {'--partition=' + resources.partition if resources.partition else ''}
    --time={resources.time}

```

Thanks,
Tom

**Comment by jdblischak** [comment]
Could try something like below?

```yaml
cluster:
  mkdir -p logs/{rule} &&
  sbatch
    {resources.partitionFlag}
    --qos={resources.qos}
    --cpus-per-task={threads}
    --mem={resources.mem_mb}
    --job-name=smk-{rule}-{wildcards}
    --output=logs/{rule}/{rule}-{wildcards}-%j.out
default-resources:
  - partitionFlag=""
  - qos=<name-of-quality-of-service>
  - mem_mb=1000
```

Example rules:


```python
rule withPartitionFlag:
    resources:
        partitionFlag="--partition=aSpecificPartition",
    shell: echo "executed on aSpecificPartition"
 
rule withoutPartitionFlag:
    shell: echo "executed on whichever partition Slurm chose"
```

Alternatively, if you have a reasonable number of partitions, you could set the default resource to be all of them. From `man sbatch`:

> If the job can use more than one  partition, specify  their  names in a comma separate list and the one offering earliest initiation will be used with no regard given to  the  partition  name  ordering  (although higher  priority  partitions  will be considered first).

So if you had 5 partitions, you could set the default to eg:

```yaml
default-resources:
  - partition=partition1,partition2,partition3,partition4,partition5
```

And then Slurm would choose the optimum partition to execute each rule.

**Comment by TomHarrop** [comment]
That’s perfect. Thank you.

**Comment by jdblischak** [comment]
@TomHarrop Which of the 2 options did you decide to use? I'd like to create and document an example based on whichever you find to be the most practical solution

**Comment by TomHarrop** [comment]
They both work!

> If not specified, the default behavior is to allow the slurm controller  to select the default partition as designated by the system administraor

I'm using option 1. I'm not sure if the behaviour described in the manual for a list of partitions ("the one offering earliest initiation") is the same as the default ("partition as designated by the system administrator"). Option 1 is also more generic.



I do like explicitly listing the available partitions in `default-resources`, and I didn't know that you could supply a list of partitions, so that could be a useful example too. 

I'd be happy to add an example for either or both.

**Comment by jdblischak** [comment]
> I'd be happy to add an example for either or both.

@TomHarrop I'd love to have you contribute either or both examples! Please see my recent commit 2df811f8a4b3eae95dae13272094cb4648a7198b for guidance on creating a new example. Thanks!
