### ISSUE TITLE
Mixing of local and cluster jobs

### ISSUE THREAD

**Issue by mhorlacher** [jdblischak/smk-simple-slurm#19]
Some rules may execute in seconds (say, checking filesize), while other may take hours and are better suited for cluster execution. Is it possible to e.g. flag rules to be run locally, while other rules are scheduled via an HPC cluster?

**Comment by jdblischak** [comment]
Yes, you can use the [`localrule`](https://snakemake.readthedocs.io/en/stable/snakefiles/rules.html#local-rules) directive
