### ISSUE TITLE
custom log dir as a variable configured from commandline or returned from a bash function

### ISSUE THREAD

**Issue by smilesun** [jdblischak/smk-simple-slurm#25]
Can I use a variable to replace "logs" in the following? 

this variable can be either configured via environment variable or returned from a bash function called here

```
  mkdir -p logs/{rule} &&
  sbatch
    --output=logs/{rule}/{rule}-{wildcards}-%j.out

```

i tried 

```
  mkdir -p {log_dir}/{rule} &&
  sbatch
    --output={log_dir}/{rule}/{rule}-{wildcards}-%j.out

```
with 

```
export log_dir="logs"
snakemake --profile=config.yaml
```

as well as 
```
snakemake --profile=config.yaml --config log_dir="logs"
```
both get the error:

I got
```


NameError: The name 'log_dir' is unknown in this context. Please make sure that you defined that variable. Also note that braces not 
used for variable access have to be escaped by repeating them, i.e. {{print $1}}, when formatting the following:
mkdir -p zoutput/{log_dir}/{rule} && sbatch --partition=gpu_p --qos=gpu_normal --gres=gpu:1 --nice=10000 -t 48:00:00 -c 2 --mem=160G 
--job-name=smk-{rule}-{wildcards} --output=zoutput/{log_dir}/{rule}/{rule}-{wildcards}-%j.ou
```

**Comment by jdblischak** [comment]
For using an environment variable, can you try ` mkdir -p $log_dir/{rule}`? The `{}` are for substituting the Snakemake fields for a given rule.

> Can I use a variable to replace "logs" in the following?

Could you help me understand the motivation? In the default, `logs` is simply the top-level log directory. If you want this to be different for your pipeline, why not just hard-code it to be something different?

I also want to note that these logs are the Slurm log files. You can have even more control over the log files if you define the [Snakemake field `log`](https://snakemake.readthedocs.io/en/v8.16.0/snakefiles/rules.html) and pass this value to your command-line tool. In other words, you can be less concerned about the Slurm log files if you control them this way.

**Comment by jdblischak** [comment]
Another idea. For increased flexibility, you can run arbitrary Python code directly in the YAML file. I've never tried this myself, but for an example see @TomHarrop's profile [petrichor.config.yaml](https://gist.github.com/TomHarrop/c860722c8f50b9d0e65f03f225a87d04)

**Comment by smilesun** [comment]
> For using an environment variable, can you try ` mkdir -p $log_dir/{rule}`? The `{}` are for substituting the Snakemake fields for a given rule.
> 
> > Can I use a variable to replace "logs" in the following?
> 
> Could you help me understand the motivation? In the default, `logs` is simply the top-level log directory. If you want this to be different for your pipeline, why not just hard-code it to be something different?
> 
> I also want to note that these logs are the Slurm log files. You can have even more control over the log files if you define the [Snakemake field `log`](https://snakemake.readthedocs.io/en/v8.16.0/snakefiles/rules.html) and pass this value to your command-line tool. In other words, you can be less concerned about the Slurm log files if you control them this way.

A short answer to the motivation:   In a cluster, one may carry out a lot of experimental settings, where each setting correspond to many jobs, i want to separate the jobs according to the settings so one could easily debug what happens to failed runs. So the slurm logs should go into separate subfolders where each sub folder correspond to one experimental setting. Does that make sense?

**Comment by smilesun** [comment]
$logdir works!

**Comment by jdblischak** [comment]
> one may carry out a lot of experimental settings, where each setting correspond to many jobs, i want to separate the jobs according to the settings so one could easily debug what happens to failed runs.

Thanks for the explanation. I assume "a lot of" implies that these experiments are being orchestrated by some sort of `for` loop, and thus the requirement that the log directory be specified as a variable.

> $logdir works!

Wonderful! Thanks for confirming. Also, if you're interested, please feel free to contribute a minimal example to this repo that demonstrates your `$logdir` motivation and strategy.
